FROM golang:1.21.0 AS builder

WORKDIR /app

COPY go.mod go.sum ./

COPY . .

RUN go build -o schedule-processor main.go

FROM gcr.io/distroless/base-debian11:nonroot

WORKDIR /

COPY --from=builder /app/schedule-processor .

EXPOSE 8080


CMD ["./schedule-processor"]
