FROM golang:1.21.0 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Copy the rest of the source code
COPY . .

RUN go build -o schedule-processor main.go

FROM gcr.io/distroless/base-debian11:nonroot

# Set the working directory inside the runtime container
WORKDIR /

# Copy the compiled binary from the builder stage
COPY --from=builder /app/schedule-processor .

# Expose a port (optional, for HTTP servers)
EXPOSE 8080

CMD ["./schedule-processor"]