# Stage 1: Build Stage
FROM golang:1.21.0 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build a statically linked binary (no `glibc` dependencies)
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o schedule-processor main.go

# Stage 2: Minimal Final Image
FROM scratch

WORKDIR /

# Copy the compiled binary from the builder stage
COPY --from=builder /app/schedule-processor .

CMD ["/schedule-processor"]
